name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 57f903fed2d5df108109d9b3ee4aaac21197f385cf41ee88c268cfade232a05d:$(date +%s)
    - name: Push the Docker image
      run: docker push 57f903fed2d5df108109d9b3ee4aaac21197f385cf41ee88c268cfade232a05d:$(date +%s)
    - name: Run the Docker image
      run: docker run 57f903fed2d5df108109d9b3ee4aaac21197f385cf41ee88c268cfade232a05d:$(date +%s)
       